# Site settings
title: CLECert
tagline: Simple CLE Certificate Generation
description: > # this means to ignore newlines until "baseurl:"
  Easily generate a CLE certificate for your learning events
baseurl: "/clecert-site" # the subpath of your site, e.g. /blog/
url: "http://clecert.com" # the base hostname & protocol for your site
faviconurl: "/favicon.ico"

# Build settings
markdown: kramdown
safe: true
exclude:
  - tests
